apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatest-chart.fullname" . }}
  labels:
    {{- include "chatest-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "chatest-chart.name" . }}
    release: {{ .Release.Name }}

